<?php
/**
 * Collection of random and general functions
 */
include_once( 'functions/initialization.php' );

/**
 * Include all of your assets ( CSS & JS )
 */
include_once( 'functions/enqueue.php' );

/**
 * Function that enable the including of an CSS & JS in any file
 *
 * Note: Do not edit this file
 */
include_once( 'functions/include-assets.php' );

/**
 * Add custom image size
 */
include_once( 'functions/image-size.php' );

/**
 * A function that enable the passing of variables in inlcuding a partial file
 *
 * Note: Do not edit this file
 */
include_once( 'functions/views.php' );

/**
 * Main setting of your backend
 *
 * Note: Not required to edit this
 */
include_once( 'functions/theme-support.php' );

/**
 * Adding of menu
 */
include_once( 'functions/menus.php' );

/**
 * Add a class in your body tag
 *
 * Note: Not required to edit this
 */
include_once( 'functions/body-class.php' );

/**
 * Setting of your website title
 *
 * Note: Not required to edit this
 */
include_once( 'functions/wp-title.php' );

/**
 * Guide in rewriting your url rules
 */
// include_once( 'functions/rewrite-rules.php' );

/**
 * To use this you need to install ACF Pro or ACF Options Plugin
 */
// include_once( 'functions/options.php' ); 

/**
 * To use this you need to install Advanced TinyMCE Plugin
 */
// include_once( 'functions/tinymce.php' );

/**
 * Customize your backend, especially your backend login page
 */
// include_once( 'functions/backend.php' );

/**
 * Enable the category in page post type
 */
// include_once( 'functions/page-cat.php' ); 

/**
 * Customize the term interface
 */
// include_once( 'functions/term-settings.php' );

/**
 * Include all the file inside the specify subfolder of functions folder
 */
include_all_php('posttype');
include_all_php('pregetpost');
include_all_php('shortcode');
include_all_php('taxonomy');

/**
 * Guid on how to name and include your AJAX Script ( PHP )
 */
// include_once( 'ajax/function-name/function-name.php' );

/**
 * Guid on how to name and include your custom script ( PHP )
 */
// include_once( 'functions/custom-*.php' );